using UnityEngine;

namespace NativeRender
{
    /// <summary>
    /// Persistent asset that stores the GPU-ready baked OMM (Opacity Micromap) output for a mesh.
    /// Generated by the Editor via NativeRender > Bake OMM for Selected Targets,
    /// which calls ommCpuBake in the native plugin and saves the result here.
    /// At runtime the pre-baked blobs are uploaded directly to the GPU — no CPU baking occurs.
    /// </summary>
    [CreateAssetMenu(menuName = "NativeRender/OMM Cache", fileName = "OMMCache")]
    public class OMMCache : ScriptableObject
    {
        public enum DownsampleFactor { x1 = 1, x2 = 2, x4 = 4, x8 = 8 }

        /// <summary>Mirrors ommFormat: OC1_2_State=1, OC1_4_State=2.</summary>
        public enum OmmFormat : byte { TwoState = 1, FourState = 2 }

        [Header("Source References (used for staleness detection)")]
        public Mesh      sourceMesh;
        /// <summary>Which submesh of sourceMesh this cache was baked for.</summary>
        public int       submeshIndex;
        public Texture2D sourceTexture;
        public float     alphaCutoff;
        [Range(0, 12)]
        public byte           maxSubdivisionLevel      = 8;
        public DownsampleFactor textureDownsampleFactor = DownsampleFactor.x1;
        /// <summary>
        /// Controls per-triangle micro-triangle density.
        /// The baker picks a subdivision level so one micro-triangle covers
        /// roughly (scale × scale) texels. 0 = disable dynamic mode (use
        /// maxSubdivisionLevel uniformly). Default 2.
        /// </summary>
        [Range(0f, 12f)]
        public float dynamicSubdivisionScale = 2f;
        public OmmFormat ommFormat = OmmFormat.FourState;

        [Header("Baked GPU Data (produced by ommCpuBake)")]
        [HideInInspector] public byte[]  bakedArrayData;      // raw OMM array bit data
        [HideInInspector] public byte[]  bakedDescArray;      // ommCpuOpacityMicromapDesc[] bytes
        public                   uint    bakedDescArrayCount;
        [HideInInspector] public byte[]  bakedIndexBuffer;    // per-triangle OMM index buffer
        public                   uint    bakedIndexCount;
        public                   uint    bakedIndexStride;    // 1, 2, or 4
        /// <summary>
        /// Flat histogram: [count, subdivisionLevel, format] uint32 triples, one per entry.
        /// Length == histogramEntryCount * 3.
        /// </summary>
        [HideInInspector] public uint[]  histogramFlat;

        /// <summary>Number of histogram entries (histogramFlat.Length / 3).</summary>
        public int HistogramEntryCount => (histogramFlat != null) ? histogramFlat.Length / 3 : 0;

        /// <summary>Returns true when all required baked blobs are present and non-empty.</summary>
        public bool IsValid =>
            bakedArrayData   != null && bakedArrayData.Length   > 0 &&
            bakedDescArray   != null && bakedDescArray.Length   > 0 &&
            bakedIndexBuffer != null && bakedIndexBuffer.Length > 0 &&
            histogramFlat    != null && histogramFlat.Length    > 0 &&
            bakedDescArrayCount > 0  && bakedIndexCount > 0;
    }
}

